### ISSUE TITLE
JSX and TSX souce code highlight

### ISSUE THREAD

**Issue by wiseqingyang** [uiwjs/npm-unpkg#21]

**Comment by jaywcjlove** [comment]
@wiseqingyang Are there examples?

**Comment by jaywcjlove** [comment]
https://uiwjs.github.io/npm-unpkg/#/pkg/uiw/file/lib/esm/index.d.ts

**Comment by wiseqingyang** [comment]
@jaywcjlove tsx 和 jsx 源码没有高亮，例子 https://uiwjs.github.io/npm-unpkg/#/pkg/@react-navigation/native/file/src/index.tsx
非常感谢

**Comment by jaywcjlove** [comment]
@wiseqingyang 其实已经高亮，高亮代码的js 是懒加载进来的，有时候网络问题会慢一些。

通过 https://uiw.gitee.io/npm-unpkg/ 速度会比较快。

 https://uiw.gitee.io/npm-unpkg/#/pkg/@react-navigation/native/file/src/index.tsx

**Comment by wiseqingyang** [comment]
可以了，谢谢
